# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a9544d887b4acea2505bf03fdf22db54975569d83d037450de461b23452cc8353e162fa4376f124846e1a6c2d83142f0cb430eb9cccebf3b2d47e1d7fffb3c9

test:
  secret_key_base: 9dca2f51c4c3fe2fa9b4c3d995b4a41fa14b7c3f8932616171ed13057904a85769bbbbd92fc737e82564ffcd6cdd48c18675a16a08a24bafa8b6777837da53be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
